import os
import shutil
import logging
from datetime import datetime

logger = logging.getLogger(__name__)

# Codeforces Rating Tiers with Colors
RATING_TIERS = [
    {"name": "Newbie", "min": 0, "max": 1199, "color": "gray"},
    {"name": "Pupil", "min": 1200, "max": 1399, "color": "green"},
    {"name": "Specialist", "min": 1400, "max": 1599, "color": "cyan"},
    {"name": "Expert", "min": 1600, "max": 1899, "color": "blue"},
    {"name": "Candidate Master", "min": 1900, "max": 2099, "color": "purple"},
    {"name": "Master", "min": 2100, "max": 2299, "color": "orange"},
    {"name": "Grandmaster", "min": 2300, "max": 9999, "color": "red"},
]

def get_tier_color(rating: int) -> str:
    """Get color for Codeforces rating tier."""
    for tier in RATING_TIERS:
        if tier["min"] <= rating <= tier["max"]:
            return tier["color"]
    return "lightgrey"

def get_tier_name(rating: int) -> str:
    """Get name for Codeforces rating tier."""
    for tier in RATING_TIERS:
        if tier["min"] <= rating <= tier["max"]:
            return tier["name"]
    return "Unrated"

class RepositoryBuilder:
    """Compiles repository structure and generates stats dashboard."""
    def __init__(self, repo_dir: str):
        self.repo_dir = repo_dir

    def sync_submission(self, sub_metadata: dict, local_src_path: str) -> str:
        """Copy local solution code to repo structure and create metadata README.

        Args:
            sub_metadata: Submission metadata dictionary.
            local_src_path: Path to the local solver source file.

        Returns:
            The path of the copied solution file relative to the repo directory.
        """
        rating = sub_metadata.get("rating")
        rating_folder = str(rating) if rating is not None else "unrated"
        
        contest_id = sub_metadata["contestId"]
        problem_index = sub_metadata["problemIndex"]
        problem_dir_name = f"{contest_id}{problem_index}"
        
        # Target directory: {repo_dir}/{rating_folder}/{problem_dir_name}/
        target_dir = os.path.join(self.repo_dir, rating_folder, problem_dir_name)
        os.makedirs(target_dir, exist_ok=True)
        
        # Copy solution file
        ext = os.path.splitext(local_src_path)[1]
        target_filename = f"solution{ext}"
        target_file_path = os.path.join(target_dir, target_filename)
        shutil.copy2(local_src_path, target_file_path)
        logger.info(f"Copied solution file to {target_file_path}")
        
        # Create problem README
        self._write_problem_readme(target_dir, sub_metadata, target_filename)
        
        return os.path.relpath(target_file_path, self.repo_dir)

    def _write_problem_readme(self, target_dir: str, meta: dict, filename: str):
        """Write problem-specific README.md with metadata."""
        readme_path = os.path.join(target_dir, "README.md")
        
        contest_id = meta["contestId"]
        idx = meta["problemIndex"]
        name = meta["problemName"]
        rating = meta.get("rating")
        tags = ", ".join(meta.get("tags", []))
        date_solved = meta["solvedDate"]
        lang = meta["language"]
        time_used = meta.get("timeConsumedMillis", 0)
        mem_used = meta.get("memoryConsumedBytes", 0) / 1024.0 # in KB
        
        # Calculate time & memory string
        time_str = f"{time_used} ms"
        mem_str = f"{mem_used:.1f} KB"
        
        rating_str = f"{rating}" if rating is not None else "Unrated"
        
        content = f"""# {name}

## Metadata
- **Problem Link:** [Codeforces - {contest_id}{idx}](https://codeforces.com/contest/{contest_id}/problem/{idx})
- **Rating:** {rating_str}
- **Language:** {lang}
- **Time Consumed:** {time_str}
- **Memory Consumed:** {mem_str}
- **Solved Date:** {date_solved}
- **Tags:** `{tags}`

## Solution File
- [Solution Source Code](./{filename})

---
*Auto-generated by [CF-Sync](https://github.com/your-username/cf-sync).*
"""
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(content)
        logger.debug(f"Wrote problem README to {readme_path}")

    def generate_dashboard(self, synced_submissions: dict):
        """Regenerate the root README.md containing the stats dashboard.

        Args:
            synced_submissions: Dictionary mapping submission ID -> metadata dict.
        """
        readme_path = os.path.join(self.repo_dir, "README.md")
        
        if not synced_submissions:
            # Write a placeholder README if empty
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write("# Codeforces Solutions\n\nNo submissions synced yet. Run `cf-sync` to fetch solutions.")
            return

        total_solved = len(synced_submissions)
        
        # Calculate metrics
        max_rating = 0
        lang_distribution = {}
        rating_distribution = {}
        tag_distribution = {}
        recent_solves = []

        # Sort submissions chronologically for processing
        sorted_subs = sorted(
            synced_submissions.values(), 
            key=lambda x: x.get("creationTimeSeconds", 0), 
            reverse=True
        )

        # We'll use a set of problem keys to avoid double-counting if a user has multiple solutions to same problem
        unique_problems = set()

        for sub in sorted_subs:
            contest_id = sub["contestId"]
            idx = sub["problemIndex"]
            prob_key = f"{contest_id}{idx}"
            
            # Count only unique solved problems for dashboard stats
            if prob_key in unique_problems:
                continue
            unique_problems.add(prob_key)

            rating = sub.get("rating")
            lang = sub.get("language", "Unknown")
            tags = sub.get("tags", [])

            # Max rating
            if rating and rating > max_rating:
                max_rating = rating

            # Language breakdown (normalize simple languages)
            simple_lang = lang.split(" (")[0].split(" - ")[0]
            # Group Python 3, PyPy, etc.
            if "Python" in simple_lang or "PyPy" in simple_lang:
                simple_lang = "Python"
            elif "C++" in simple_lang:
                simple_lang = "C++"
            
            lang_distribution[simple_lang] = lang_distribution.get(simple_lang, 0) + 1

            # Rating distribution
            if rating is not None:
                rating_distribution[rating] = rating_distribution.get(rating, 0) + 1
            else:
                rating_distribution["Unrated"] = rating_distribution.get("Unrated", 0) + 1

            # Tag distribution
            for tag in tags:
                tag_distribution[tag] = tag_distribution.get(tag, 0) + 1

            # Recent solves (keep top 10 unique solves)
            if len(recent_solves) < 10:
                recent_solves.append(sub)

        # Generate text-based progress bars
        max_rating_count = max(rating_distribution.values()) if rating_distribution else 1
        sorted_ratings = sorted(
            [r for r in rating_distribution.keys() if isinstance(r, int)]
        )
        if "Unrated" in rating_distribution:
            sorted_ratings.append("Unrated")

        # HTML table for rating breakdown
        rating_breakdown_html = "<table>\n  <tr><th>Rating</th><th>Count</th><th>Bar</th></tr>\n"
        for r in sorted_ratings:
            count = rating_distribution[r]
            pct = int((count / max_rating_count) * 100)
            color = get_tier_color(r) if isinstance(r, int) else "lightgrey"
            # Visual ASCII/Unicode bar
            bar_len = int(pct / 5)
            bar_str = "█" * bar_len + "░" * (20 - bar_len)
            rating_breakdown_html += f"  <tr><td><b>{r}</b></td><td>{count}</td><td><code>{bar_str}</code></td></tr>\n"
        rating_breakdown_html += "</table>"

        # Languages list
        sorted_langs = sorted(lang_distribution.items(), key=lambda x: x[1], reverse=True)
        lang_markdown = "\n".join([f"- **{l}**: {c} solved" for l, c in sorted_langs])

        # Topics list (Top 10)
        sorted_tags = sorted(tag_distribution.items(), key=lambda x: x[1], reverse=True)[:10]
        tag_markdown = "\n".join([f"- **{t}**: {c} solved" for t, c in sorted_tags])

        # Recent solves markdown
        recent_markdown = "| Problem | Rating | Language | Date Solved | Link |\n| :--- | :--- | :--- | :--- | :--- |\n"
        for sub in recent_solves:
            contest_id = sub["contestId"]
            idx = sub["problemIndex"]
            name = sub["problemName"]
            rating = sub.get("rating", "Unrated")
            lang = sub.get("language", "Unknown")
            date = sub["solvedDate"]
            
            # Find the path in repo relative to root
            rating_folder = str(rating) if isinstance(rating, int) else "unrated"
            sol_link = f"./{rating_folder}/{contest_id}{idx}/"
            
            recent_markdown += f"| [{contest_id}{idx} - {name}](https://codeforces.com/contest/{contest_id}/problem/{idx}) | {rating} | {lang} | {date} | [View Solution]({sol_link}) |\n"

        # Problem Index (Complete searchable list)
        index_markdown = "| Code | Problem Title | Rating | Language | Date Solved | Link |\n| :--- | :--- | :--- | :--- | :--- | :--- |\n"
        for sub in sorted_subs:
            contest_id = sub["contestId"]
            idx = sub["problemIndex"]
            name = sub["problemName"]
            rating = sub.get("rating", "Unrated")
            lang = sub.get("language", "Unknown")
            date = sub["solvedDate"]
            
            rating_folder = str(rating) if isinstance(rating, int) else "unrated"
            sol_link = f"./{rating_folder}/{contest_id}{idx}/"
            
            index_markdown += f"| {contest_id}{idx} | [{name}](https://codeforces.com/contest/{contest_id}/problem/{idx}) | {rating} | {lang} | {date} | [View Solution]({sol_link}) |\n"

        # Badge URL creation
        tier_name = get_tier_name(max_rating) if max_rating > 0 else "Unrated"
        badge_color = get_tier_color(max_rating)
        
        solved_badge = f"![Solved Problems](https://img.shields.io/badge/Solved-{len(unique_problems)}_Problems-blue?style=flat-square&logo=codeforces)"
        max_rating_badge = f"![Max Rating](https://img.shields.io/badge/Max_Rating-{max_rating}-{badge_color}?style=flat-square)"
        tier_badge = f"![Tier](https://img.shields.io/badge/Tier-{tier_name.replace(' ', '_')}-{badge_color}?style=flat-square)"

        # Assemble main README content
        readme_content = f"""# Codeforces Submissions

Syncing accepted solutions automatically.

<p align="left">
  {solved_badge}
  {max_rating_badge}
  {tier_badge}
</p>

---

## 📊 Statistics Dashboard

### Rating Distribution
{rating_breakdown_html}

<br>

### 🛠️ Languages Used
{lang_markdown}

<br>

### 🏷️ Top Topics & Tags
{tag_markdown}

---

## 🕒 Recent Solves
{recent_markdown}

---

## 🗂️ Solved Problems Index
<details>
<summary><b>Click to expand full index ({len(unique_problems)} problems)</b></summary>

{index_markdown}
</details>

---
*Last updated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}*  
*Auto-compiled by [CF-Sync](https://github.com/your-username/cf-sync).*
"""
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)
        logger.info(f"Dashboard README regenerated successfully at {readme_path}")
